class base_vseq extends uvm_sequence #(uvm_sequence_item);  
`uvm_object_utils(base_vseq)

packet_sequencer sequencer[router_pkg::NPORT];

// set the input router port where the sequence will inject its packets. default is 0
bit [3:0] port;
// set the # of packets generated by the sequence. default is 50
int npackets;

function new(string name = "base_vseq");
  super.new(name);
  npackets = 50;
  port = 0;
endfunction: new

endclass: base_vseq

