/*
 this sequence inject packets in a single port
*/
class basic_seq extends uvm_sequence #(packet_t); 
`uvm_object_utils(basic_seq)

// set the input router port where the sequence will inject its packets. default is 0
bit [3:0] port;
// set the # of packets generated by the sequence. default is 50
int npackets;

function new(string name = "");
  super.new(name);
  npackets = 50;
  port = 0;
endfunction: new

task body;
  packet_t tx;
  repeat(npackets)
  begin
    tx = packet_t::type_id::create("tx");
    // set the driver port where these packets will be injected
    tx.dport = port;
    // disable packets with zero payload
    tx.w_zero = 0;
    start_item(tx);
    // create only small packets
    assert(tx.randomize() with {tx.p_size == SMALL;});
    //assert(tx.randomize());
    //assert(tx.randomize() with {tx.payload.size() == 1;});
    finish_item(tx);
  end
endtask: body

endclass: basic_seq

